### ISSUE TITLE
Integrate Config Split for development process.

### ISSUE THREAD

**Issue by ozin7** [lemberg/draft#1]
[Config Split ](https://www.drupal.org/project/config_split) simplify development process when need to have some specific configuration per environment, standard case when you need the devel module to be  enabled. 
## How it works:
This module split configuration and generate them into specific folders. When you run  `drush csex/csim` it use default configurations + split configurations. Some work example of the **config_split.config_split.develop.yml**:

```
uuid: c4ae95f9-ad0e-4bca-bbae-99da2c69a6e8
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: 0ldk7pql2cgIPGJNcdPkkV7OQ3RbS0okRw9CHKULFT0
id: develop
label: Develop
folder: ../config/develop
module:
  devel: 0
theme: {  }
blacklist: {  }
graylist:
  - core.extension
graylist_dependents: true
graylist_skip_equal: true
weight: 0
```

## How to use:
1) Use `drush csex/csim` on your develop environments
2) On production use default `drush cex/cim` and disable develop split in the settings.php `$config['config_split.config_split.develop']['status'] = FALSE;`

## Specific for the Draft:
When you install Draft profile default Develop Split configuration is imported. Those configuration is empty and just define Develop Split. When you start working on your project you will need to add filter modules(devel, field_ui, views_ui etc) to the Develop Split and run `drush csex`, it will generate split configurations for the Develop Split into the .`./config/develop` folder. Enjoy!
